<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ika_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for TEKNOFEST 2026 UGV</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>ika_control</exec_depend>
  <exec_depend>ika_vision</exec_depend>
  <exec_depend>ika_decision</exec_depend>
  <exec_depend>ika_bridge</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
